[providers.local]
type = "age"
recipients = [
    "age1qwpvqqcy8tcvtekm94hmjhmeylmd6nr00sd7plsx4vu6s7z8wyxsk9ex2a",
    "age197tjyxyy77q59zlah75dqcz259y930qe78e3pd7jwvfadacksu6qlxhg5w",
]

[providers.onepass]
type = "1password"
vault = "Development"

[secrets.MY_SECRET]
provider = "local"
value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWa25ZalFqbEk3WUZ3TGpTNzNiNlRzN0Q1TWFCeWNRZm8vMnVaMWNPNENnCk5GcnlPdlJjczd2K3Nqdzd3VjEyeitxbmwxWGRramdmZ0NhQXpQOFl1UHMKLT4gWDI1NTE5IGg0NXNUaSt0Ly9Ba3JPWktmZTVXUzZUTUdreHVZY283VmhlaCt3QTNqakUKTEFVdGltS2lqWVRxV0YxOTVUZkVUM21UMXZBenQvUmVvbjRCOUY5em9PdwotLS0gTFc2LzV2dTNPZGdUZ1hPRDlLVnJtVmlRZXluRTBKOHM4U1Frd29jQ1BOVQphAokPlig9OJ2fn5eK6hAgy/BtS39aTCfcpahHoIORqknyiBvG"

[secrets.NEW_SECRET]
provider = "local"
value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRDRXQnVMVmxpQnpMOHpwM094TXdXSHJHNml6SGtFcU9aRm8rbTNzR0VRCkh6TlRWYm1OS2FyRUVoS05MU2p6dVpCRjczSTJJNEZhSEtwRittVmNZejgKLT4gWDI1NTE5IFRJeUhwUlRraHhsZS92aXRaTDhpVHRKSWNVREw2UEM5Z3YxY3ZwMmM4RDQKYUZ4YTFDb09HN2RYNVNsa29ZQ2pxQit2SmRqQTZzZmJrQm9pN3VhdTNKWQotLS0gTXFEN2Y3UUQwbVplZlZEbndwb0g4a0dGMHZZUnRDaWpCTjc3NTM2RGxsWQrd5zB5gsHiErhjCiS2zsYW9k7D48+q/IT/GjJvRfHyw6J5N8s3"

[secrets.OP_SERVICE_ACCOUNT_TOKEN]
provider = "local"
value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1c2UwaGNwNmVDWGZSYVhjRlFwcTZyR0RBeGV1QWpkcExLSCtBZC9zZkhnCnAxazlicGtYa1NQTGJpa3N6UTU0Rk42TGpQSW1seWd3VmtFeVhrTGF4akkKLS0tIDhvYmtWS1hxNEQ0QW4wcWxHNnlnUFJqTGI5YUMxUUJSVk15OXBMZHpQSzAKoJOq3Rj4nSRj3nOop6j8W+6K85r/xiG2hum6vC8zqFgmDCmPRfLDtinQmqlor1+92dX05rzYt9NS8E5Q73RBumLoNJKUBn9hNta8PETrJItXUyx31F2BUnRkCNSibPIFRGWJWGIQJKcd/LeIcxCQwXqCu011Cf1O+GQazQzptI4eHI2uYKlWjJanQ/Li40p/Syg+B/XI8asAmr2e007/6XrEQ9mw61nBc0Q835YA0SUyvglNZyJDxpF3yQHsSW8H/SdG9T/LgD6GXNZaDTLL5qz2MIKUwDzNrhBYsjc+7sqkhUR+C2cQhrGbkzkMBiAZhG8hZL3BpkB5VYYBDPBZhOidJgISXp0Klx5KTWW+aMJWqE15nM3eYrdgwZYUJEEAP4IUA1/VLmHgYjR08DT81pKOgeB39BWWgJ5mO5QseZ4KZg0ZlV2Alr3l2mbVp0SFaeEtMlMMS6R/rO2JGtcs9WJ+GaGCtkKw6x65Wpsqau61rJOcMtX4EwKamEmWezS7U+kexD2sk4gJZ3DSPR77nK2Feq6+Tf7tMdtAFfIzesI2cwhittAbGsysebNBLn2VYrCE1SXjfl+MFX6Sw/VUBiRYWVn0uGMd40y0WezKc47I0+S2fqkJRs5jB1fVui6YI73FMD8IvnP/KEH955ov5T/wT8YAcCLHnclJUMO76tWObNFPrFj2h0hSaTLe6Ff8yaKNV12FsCHbO1yw8pzuQ2HdhivQfvT+Gcxluog5g0JEfwRVfq8s8NEL4kefvqY4cOQ1IDxRyhmEVEjrTBWcdwTT+zDN7+paPPgXuiSM741bIJLz4ChYI7UTcsm7iua7Un897Td8BHK8DqRVYXV+Dvd2bhk9MQOh3sqAoAKDhASdEjfd+rAuKgCMlp0hi6CALFw6CXhNZyab2RXlw/NfBIBnVpPh5xeaFsvsnIaTCl77D1ajjKO14JulOXYvzVohyMYHaEqBvUjWU9KCuEC5xncOvW9BVqJTixeDmzAdOvJY4mITKr6YKtZGxHOSH1nVisVo5hxApivwFfouUsAdeFqE2R52YKZ4c9XDzDoQM/Kj70bAB9JezMa4dKBdl1Q09zD7+/QhRhnuXDV8hYvt7N4aa8aygthCxHfjgGeACdCCc5TgzAWKjnrtT5ZmeKMRHPZkkiIKTmoF2ps/S798qi6TtkM="

[secrets.DATABASE_PASSWORD]
provider = "onepass"
value = "Database"
